kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-selector-example
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mypvsc2
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: hostpath
